# Generated by Django 3.1.1 on 2021-04-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='salonlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='salonreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=250)),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.salonlogin')),
            ],
        ),
        migrations.CreateModel(
            name='clientreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=250)),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clientlogin')),
            ],
        ),
    ]
