# Generated by Django 3.1.1 on 2021-04-23 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='salondetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salon_name', models.CharField(max_length=50)),
                ('Opening_hours', models.CharField(max_length=50)),
                ('Services', models.CharField(max_length=300)),
                ('Service_price', models.CharField(max_length=350)),
                ('Image', models.ImageField(upload_to='images')),
                ('Address', models.CharField(max_length=250)),
                ('Login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.salonlogin')),
            ],
        ),
    ]
