# Generated by Django 3.1.1 on 2021-04-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_salondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lid', models.CharField(max_length=50)),
                ('Slid', models.CharField(max_length=50)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Mobile', models.CharField(max_length=20)),
                ('Services', models.CharField(max_length=40)),
                ('Date', models.CharField(max_length=50)),
                ('Time', models.TimeField()),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
