# Generated by Django 3.1.1 on 2021-05-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_bookingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uid', models.CharField(max_length=50)),
                ('Sid', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Review', models.CharField(max_length=250)),
            ],
        ),
    ]
