# Generated by Django 3.1.1 on 2021-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlogin',
            name='Password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='clientreg',
            name='Password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='salonlogin',
            name='Password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='salonreg',
            name='Password',
            field=models.CharField(max_length=250),
        ),
    ]
